### ISSUE TITLE
Error: Call by var for arg no. 5 has to match exactly: Got "LongWord" expected "QWord"

### ISSUE THREAD

**Issue by bonanza333** [EUOCheffe/easyuo#3]
Hi

I'm tring to compile project or debug run with Lazarus but keep having theese errors;

![image](https://user-images.githubusercontent.com/32964984/52064726-dbc87d00-257d-11e9-8101-a1c06d79c219.png)

**Comment by EUOCheffe** [comment]
ReadProcessMemory is the central function that is used to access the client's memory. You're probably using a 64bit version of the Win32 library. QWord is 8 bytes whereas we need a 4-byte DWord/Cardinal. EasyUO is really a 32bit application. Maybe there is a ReadProcessMemory32 function which uses the 4-byte version? You could simply use QWord instead of DWord/Cardinal but I'm not sure if it will still work. Did you install a 64-bit version of Lazarus or did you specify 64bit in the project settings? You should really switch to 32bit. I have really no idea if the code works for 64bit.

**Comment by bonanza333** [comment]
I will try tommorrow and reply to you my friend thank you for quickest reply.

**Comment by bonanza333** [comment]
Its worked with Lazarus 32 bit, we can close but cant worked on client i willl send private message to you if its possible ?

Thank you
